import type { KpiDefaultPolicy } from './types'

export const DEFAULT_KPI_POLICY: KpiDefaultPolicy = {
  levels: ['pt1_tn', 'pt1_pc', 'pt2', 'senior', 'shift_leader'],
  score_scale: [1, 2, 3, 4, 5],
  monthly_appeal_hours: 48,
  people_decision_appeal_business_days: 3,
  minimum_monthly_hours_for_full_kpi: 80,
  groups: [
    {
      id: 'grp_revenue',
      name: 'Doanh thu',
      tag: 'revenue',
      weight: 25,
      promotion_core: false,
      sort_order: 1,
      criteria: [
        {
          id: 'revenue_output',
          group_id: 'grp_revenue',
          name: 'Kết quả doanh thu theo ca',
          description: 'Đo theo dữ liệu bán hàng đã chốt cho vị trí và số giờ tham gia trong kỳ.',
          scoring_mode: 'automatic',
          weight: 25,
          source_key: 'pos.revenue_shift_index',
          score_bands: [
            { min: 95, max: null, score: 5 },
            { min: 90, max: 94.99, score: 4 },
            { min: 80, max: 89.99, score: 3 },
            { min: 70, max: 79.99, score: 2 },
            { min: 0, max: 69.99, score: 1 },
          ],
          adjustment_reason_required: true,
          applies_when: { min_hours: 80 },
          sort_order: 1,
          active: true,
        },
      ],
    },
    {
      id: 'grp_customer_service',
      name: 'Dịch vụ và trải nghiệm khách hàng',
      tag: 'customer_service',
      weight: 25,
      promotion_core: true,
      sort_order: 2,
      criteria: [
        {
          id: 'customer_feedback',
          group_id: 'grp_customer_service',
          name: 'Điểm trải nghiệm khách hàng',
          description: 'Tổng hợp phản hồi khách, food app và điểm phục vụ theo rubric đã công bố.',
          scoring_mode: 'combined',
          weight: 25,
          source_key: 'service.customer_experience_index',
          score_bands: [
            { min: 4.7, max: null, score: 5 },
            { min: 4.4, max: 4.69, score: 4 },
            { min: 4.0, max: 4.39, score: 3 },
            { min: 3.5, max: 3.99, score: 2 },
            { min: 0, max: 3.49, score: 1 },
          ],
          evidence_required_below: 3,
          adjustment_reason_required: true,
          sort_order: 1,
          active: true,
        },
      ],
    },
    {
      id: 'grp_operations',
      name: 'Vận hành và tuân thủ',
      tag: 'operations',
      weight: 25,
      promotion_core: true,
      sort_order: 3,
      criteria: [
        {
          id: 'operations_accuracy',
          group_id: 'grp_operations',
          name: 'Độ chính xác vận hành',
          description: 'Đo từ checklist ca, lỗi nhập POS và tuân thủ SOP đã xác nhận nguồn.',
          scoring_mode: 'combined',
          weight: 25,
          source_key: 'operations.compliance_index',
          score_bands: [
            { min: 97, max: null, score: 5 },
            { min: 93, max: 96.99, score: 4 },
            { min: 88, max: 92.99, score: 3 },
            { min: 80, max: 87.99, score: 2 },
            { min: 0, max: 79.99, score: 1 },
          ],
          evidence_required_below: 3,
          adjustment_reason_required: true,
          sort_order: 1,
          active: true,
        },
      ],
    },
    {
      id: 'grp_discipline',
      name: 'Kỷ luật và thực thi',
      tag: 'discipline',
      weight: 25,
      promotion_core: true,
      sort_order: 4,
      criteria: [
        {
          id: 'discipline_execution',
          group_id: 'grp_discipline',
          name: 'Kỷ luật ca làm và phản hồi vi phạm',
          description: 'Tổng hợp chấm công, hồ sơ sự cố đã xác nhận và mức tuân thủ quyết định vận hành.',
          scoring_mode: 'combined',
          weight: 25,
          source_key: 'discipline.execution_index',
          score_bands: [
            { min: 97, max: null, score: 5 },
            { min: 93, max: 96.99, score: 4 },
            { min: 88, max: 92.99, score: 3 },
            { min: 80, max: 87.99, score: 2 },
            { min: 0, max: 79.99, score: 1 },
          ],
          evidence_required_below: 4,
          adjustment_reason_required: true,
          sort_order: 1,
          active: true,
        },
      ],
    },
  ],
  grades: [
    { code: 'excellent', name: 'Xuat sac', min_score: 4.5, max_score: 5 },
    { code: 'good', name: 'Tot', min_score: 3.8, max_score: 4.49 },
    { code: 'fair', name: 'Dat', min_score: 3, max_score: 3.79 },
    { code: 'warning', name: 'Can dao tao lai', min_score: 2, max_score: 2.99 },
    { code: 'critical', name: 'Can xu ly ngay', min_score: 1, max_score: 1.99 },
  ],
  promotion_paths: [
    {
      from: 'pt1_pc',
      to: 'pt2',
      minimum_months: 3,
      required_average_score: 3.5,
      minimum_monthly_score: 3,
      core_group_average_score: 3.5,
      disqualifying_incident_lookback_months: 6,
      active_warning_lookback_months: 6,
      test_score_threshold: 80,
      challenge_duration_months: '1',
    },
    {
      from: 'pt2',
      to: 'senior',
      minimum_months: 6,
      required_average_score: 3.8,
      minimum_monthly_score: 3.5,
      core_group_average_score: 3.8,
      required_high_months: 4,
      required_high_month_score: 3.5,
      disqualifying_incident_lookback_months: 12,
      active_warning_lookback_months: 6,
      test_score_threshold: 80,
      challenge_duration_months: '2',
    },
    {
      from: 'senior',
      to: 'shift_leader',
      minimum_months: 6,
      required_average_score: 4,
      minimum_monthly_score: 4,
      core_group_average_score: 4,
      required_high_months: 3,
      required_high_month_score: 4,
      disqualifying_incident_lookback_months: 12,
      active_warning_lookback_months: 12,
      test_score_threshold: 85,
      challenge_duration_months: '2-3',
    },
  ],
}
